from countryinfo import CountryInfo

name = input("Enter the country name: ")
cp = CountryInfo(name)

print("The country capital is:", cp.capital())
print("Your country's alternate spellings:", cp.alt_spellings())
print("Your country's total area is:", cp.area())
print("These are your country's total borders:", cp.borders())
print("Your country's calling code is:", cp.calling_codes())
print("Your country's currency is:", cp.currencies())
print("Demonym:", cp.demonym())
print("Flag:", cp.flag())
print("Geo JSON data:", cp.geo_json())
print("Information about the country:", cp.info())
print("ISO codes:", cp.iso())
print("Languages spoken in the country:", cp.languages())
print("Latitude and longitude:", cp.latlng())
print("Country name:", cp.name())
print("Native name:", cp.native_name())
print("Population:", cp.population())
print("Provinces/States:", cp.provinces())
print("Region:", cp.region())
print("Subregion:", cp.subregion())
print("Timezones:", cp.timezones())
print("Top-level domain:", cp.tld())
print("Translations:", cp.translations())
print("Wikipedia URL:", cp.wiki())
